/**
 * FILE: runtimeConfigGenerator.ts
 * PATH: packages/cli-kit/src/codegen/runtimeConfigGenerator.ts
 *
 * WHAT: Generates armemon/runtime.generated.ts — static imports of every
 *       selected plugin's runtime export plus every wizard-decided RuntimeConfig
 *       value, registered with @armemon-library/core so App.tsx needs zero manual wiring.
 *       Also generates armemon/runtime.config.ts, the hand-editable companion
 *       where app authors add their own init tasks.
 * WHY:  This replaces the reference CLI's virtual-package approach with a real,
 *       versionable file using each plugin's explicit runtimeExportName. It emits
 *       the FULL config rather than a fixed {plugins, userTasks: []} pair, because
 *       the fixed pair made six of core's seven RuntimeConfig fields unreachable
 *       from any scaffolded app and silently discarded real wizard answers — the
 *       splash wizard asked for a minimum splash duration, wrote it to a config file
 *       nothing imported, and the value never reached core. Anything a wizard can
 *       decide now arrives here through PluginInstallPlan.runtimeConfigContributions.
 *
 *       userTasks are deliberately NOT emitted into the .generated file: a file
 *       named "generated" is one people rightly expect to be overwritten, so the
 *       generated module imports them from a sibling runtime.config.ts that armemon
 *       writes once and never touches again.
 * HOW:  Given an ordered plugin list and a merged contributions object, emits one
 *       aliased import per plugin, one per component override, then a single
 *       registerRuntimeConfig() call. Component overrides are import specs rather
 *       than values because this is source-text generation.
 * WHEN: Called once, near the end of the init flow, after every plugin's plan() has
 *       been collected.
 *
 * EXPORTS: generateRuntimeConfigSource, generateUserRuntimeConfigSource,
 *          writeRuntimeConfig, RuntimeCodegenPlugin, RuntimeCodegenOptions
 * DEPENDS ON: node:path, node:fs/promises, @armemon-library/config-types
 * USED BY: packages/cli-armemon/src/flows/initReactNative.ts
 */

import path from 'node:path';
import fs from 'node:fs/promises';
import type { AppLanguage, AppLayout, RuntimeConfigContributions } from '@armemon-library/config-types';
import { readLayout } from '../fs/layout.js';

export interface RuntimeCodegenPlugin {
  packageName: string;
  runtimeExportName: string;
}

export interface RuntimeCodegenOptions {
  orderedPlugins: RuntimeCodegenPlugin[];
  contributions?: RuntimeConfigContributions;
  language?: AppLanguage;
  /** Where the managed zone is; read from disk when the caller doesn't say. */
  layout?: AppLayout;
}

export function generateRuntimeConfigSource(options: RuntimeCodegenOptions): string {
  const { orderedPlugins, contributions = {} } = options;
  // This file is written straight to disk rather than going through the JavaScript
  // conversion, so the sibling it names has to be spelled for the app's language
  // here — a JavaScript app has no runtime.config.ts to be pointed at.
  const siblingConfig = `./runtime.config${options.language === 'javascript' ? '.js' : '.ts'}`;

  const importLines = orderedPlugins.map(
    (plugin, index) =>
      `import { ${plugin.runtimeExportName} as plugin${index} } from '${plugin.packageName}';`,
  );

  const configLines: string[] = [];

  if (contributions.splashScreenComponent) {
    importLines.push(
      `import { ${contributions.splashScreenComponent.importName} as SplashScreenComponent } from '${contributions.splashScreenComponent.from}';`,
    );
    configLines.push('  SplashScreenComponent,');
  }
  if (contributions.errorScreenComponent) {
    importLines.push(
      `import { ${contributions.errorScreenComponent.importName} as ErrorScreenComponent } from '${contributions.errorScreenComponent.from}';`,
    );
    configLines.push('  ErrorScreenComponent,');
  }
  if (typeof contributions.minSplashDurationMs === 'number' && contributions.minSplashDurationMs > 0) {
    configLines.push(`  minSplashDurationMs: ${contributions.minSplashDurationMs},`);
  }
  if (contributions.readyCustom) {
    configLines.push('  readyCustom: true,');
    if (typeof contributions.readyCustomTimeout === 'number') {
      configLines.push(`  readyCustomTimeout: ${contributions.readyCustomTimeout},`);
    }
  }

  const pluginList = orderedPlugins.map((_, index) => `plugin${index}`).join(', ');

  return `// GENERATED BY ARMEMON — kept up to date by \`armemon plugin add\` and \`plugin remove\`.
// Don't edit this file; put your own init tasks and overrides in ${siblingConfig} instead.
import { registerRuntimeConfig } from '@armemon-library/core';
${importLines.join('\n')}
import { userTasks, runtimeOverrides } from './runtime.config';

registerRuntimeConfig({
  plugins: [${pluginList}],
  userTasks,
${configLines.join('\n')}${configLines.length > 0 ? '\n' : ''}  // Spread last so anything you set in runtime.config wins over the values the
  // wizard chose. That file is yours; this one is regenerated.
  ...runtimeOverrides,
});
`;
}

/**
 * The comment block written at the top of every app's runtime.config.
 *
 * Deliberately exhaustive. The point of the generated config files is that a user
 * never has to leave the editor to find out what an option is called or what it
 * does — read, uncomment, adjust. That is worth more here than anywhere else,
 * because TaskObject has fourteen fields and no obvious place to discover them.
 */
const TASK_DOC_COMMENT = `/**
 * Your app's own startup tasks.
 *
 * Written once by 'armemon init' and never overwritten — unlike
 * ./runtime.generated next to it, which armemon rewrites as plugins come and go.
 *
 * Tasks run while the splash screen is up, before your app renders. Every option is
 * documented below with an example; uncomment what you need.
 *
 * --- The shape ---------------------------------------------------------------
 *
 *   A plain async function is a task:
 *     async () => { await warmCache(); }
 *
 *   An object gives you everything else:
 *     { name: 'fetch-config', task: async (ctx) => {}, ...options below }
 *
 * --- Phases ------------------------------------------------------------------
 *
 *   phase: 'KIT_SETUP'     runs first — anything later tasks depend on
 *   phase: 'PLUGIN_INIT'   the default
 *   phase: 'USER_TASKS'    runs last
 *
 *   Phases are barriers: every KIT_SETUP task finishes before any PLUGIN_INIT task
 *   starts. So dependsOn is only ever needed within a phase, never across them.
 *
 * --- Failure and timing ------------------------------------------------------
 *
 *   critical: false     a failure is logged and startup continues. Use it for
 *                       anything optional. Default true: a failure shows the
 *                       error screen.
 *   timeout: 15000      ms before the task is abandoned. Default 180000, and
 *                       enforced whether or not your code checks ctx.signal.
 *   retries: 3          extra attempts after the first failure. Default 0.
 *   retryStrategy       'linear' (1s, 2s, 3s...) or 'exponential' (1s, 2s, 4s...)
 *   retryDelay: 1000    base delay between attempts
 *   maxRetryDelay       cap on the backoff
 *
 * --- Ordering and concurrency ------------------------------------------------
 *
 *   background: true    fire and forget — does not hold up the splash, and a
 *                       failure is logged rather than fatal
 *   parallel: true      run alongside other parallel tasks at the same step
 *   group: 'network'    only run in parallel with tasks sharing this group
 *   id / dependsOn      explicit ordering: dependsOn: ['load-cache']
 *   index: 10           tie-break between otherwise unordered tasks
 *   runIf: () => bool   skip unless this returns true (may be async)
 *
 * --- ctx ---------------------------------------------------------------------
 *
 *   ctx.signal              an AbortSignal, aborted when the timeout fires
 *   ctx.abortable(promise)  rejects on timeout instead of hanging — wrap any
 *                           fetch or long wait in it so cancellation is real
 *
 * --- Worked examples ---------------------------------------------------------
 *
 *   import { TaskPresets } from '@armemon-library/core';
 *
 *   export const userTasks = [
 *     // the simplest possible task
 *     async () => { await warmCache(); },
 *
 *     // must finish before anything else runs
 *     {
 *       id: 'load-cache',
 *       name: 'Loading cache',
 *       phase: 'KIT_SETUP',
 *       task: async () => { await cache.hydrate(); },
 *     },
 *
 *     // waits for that one, retries, and can genuinely be cancelled
 *     {
 *       name: 'Checking session',
 *       dependsOn: ['load-cache'],
 *       retries: 2,
 *       retryStrategy: 'exponential',
 *       timeout: 10000,
 *       task: async (ctx) => {
 *         const res = await ctx.abortable(fetch('https://example.com/me'));
 *         await session.apply(await res.json());
 *       },
 *     },
 *
 *     // these two run at the same time
 *     { name: 'Prefetch A', parallel: true, task: () => prefetchA() },
 *     { name: 'Prefetch B', parallel: true, task: () => prefetchB() },
 *
 *     // never blocks startup, never breaks it
 *     {
 *       name: 'Analytics',
 *       background: true,
 *       critical: false,
 *       task: async () => { await analytics.init(); },
 *     },
 *
 *     // only on a fresh install
 *     {
 *       name: 'First-run setup',
 *       runIf: async () => !(await storage.getItem('seen')),
 *       task: async () => { await seedDefaults(); },
 *     },
 *
 *     // shorthand for retries: 3 + exponential backoff + a 15s timeout
 *     TaskPresets.network({ name: 'Sync', task: (ctx) => sync(ctx) }),
 *   ];
 *
 *   The five presets, each taking the same task object:
 *     TaskPresets.network(task)            retries 3, exponential, 15s timeout
 *     TaskPresets.background(task)         background: true
 *     TaskPresets.parallel(task)           parallel: true
 *     TaskPresets.critical(task)           critical: true
 *     TaskPresets.conditional(task, runIf) runs only when runIf() resolves true
 *
 * --- Watching progress -------------------------------------------------------
 *
 *   Any component rendered during startup can read it:
 *     const { currentTask, completedTasks, totalTasks } = useTaskProgress();
 *
 * --- Holding the splash open yourself ----------------------------------------
 *
 *   Set readyCustom below to keep the splash up past task completion, then call
 *   notifyReady() when you decide you are ready:
 *     const { notifyReady } = useKitReady();
 */`;

/**
 * The doc block for the second export in runtime.config.
 *
 * Without runtimeOverrides, five of RuntimeConfig's seven fields were reachable
 * only by editing runtime.generated — a file whose first line tells you not to,
 * and which armemon rewrites whenever a plugin is added or removed. This gives them a home the app
 * author owns.
 */
const OVERRIDES_DOC_COMMENT = `/**
 * Everything else armemon registers at startup.
 *
 * ./runtime.generated is rewritten whenever a plugin is added or removed, so it is
 * the wrong place to change anything. It spreads this object in LAST instead — so a
 * field you set here overrides whatever the wizard picked, and survives the rewrite.
 *
 * Every field, all optional:
 *
 *   SplashScreenComponent   the component shown while startup tasks run.
 *                           Defaults to the one in ../splash.
 *                             import MySplash from './MySplash';
 *                             SplashScreenComponent: MySplash,
 *
 *   ErrorScreenComponent    shown when a critical task fails. Receives { error }.
 *                           Point it at a component file — this is a config
 *                           module, so keep JSX out of it.
 *                             import ErrorScreen from './ErrorScreen';
 *                             ErrorScreenComponent: ErrorScreen,
 *
 *   minSplashDurationMs     floor on how long the splash stays up, so a fast cold
 *                           start doesn't flash. Set in ../splash/splash.config;
 *                           override here to win over it.
 *                             minSplashDurationMs: 1200,
 *
 *   readyCustom             true = don't hide the splash when tasks finish; wait
 *                           for your notifyReady() call (see above).
 *                             readyCustom: true,
 *
 *   readyCustomTimeout      ms before armemon gives up waiting for notifyReady()
 *                           and shows the app anyway. Keeps a forgotten call from
 *                           stranding users on the splash forever.
 *                             readyCustomTimeout: 10000,
 */`;

export function generateUserRuntimeConfigSource(language: AppLanguage = 'typescript'): string {
  if (language === 'javascript') {
    return `${TASK_DOC_COMMENT}

export const userTasks = [];

${OVERRIDES_DOC_COMMENT}
export const runtimeOverrides = {};
`;
  }

  return `${TASK_DOC_COMMENT}
import type { TaskFn, TaskObject } from '@armemon-library/config-types';
import type { RuntimeConfig } from '@armemon-library/core';

export const userTasks: Array<TaskFn | TaskObject> = [];

${OVERRIDES_DOC_COMMENT}
export const runtimeOverrides: Partial<Omit<RuntimeConfig, 'plugins' | 'userTasks'>> = {};
`;
}

export async function writeRuntimeConfig(
  appRoot: string,
  options: RuntimeCodegenOptions,
): Promise<void> {
  // The managed zone, wherever this app keeps it — `armemon/`, or `src/armemon/` in an
  // app scaffolded before the move.
  const layout = options.layout ?? (await readLayout(appRoot));
  const dir = path.join(appRoot, ...layout.managed.split('/'));
  await fs.mkdir(dir, { recursive: true });

  const language = options.language ?? 'typescript';
  const extension = language === 'javascript' ? 'js' : 'ts';

  await fs.writeFile(
    path.join(dir, `runtime.generated.${extension}`),
    generateRuntimeConfigSource(options),
    'utf8',
  );

  // Written only if absent: this file belongs to the app author from here on.
  const userConfigPath = path.join(dir, `runtime.config.${extension}`);
  const exists = await fs
    .access(userConfigPath)
    .then(() => true)
    .catch(() => false);
  if (!exists) {
    await fs.writeFile(userConfigPath, generateUserRuntimeConfigSource(language), 'utf8');
  }
}
