/**
 * FILE: userGuide.ts
 * PATH: packages/cli-armemon/src/userGuide.ts
 *
 * WHAT: The user guide as published in the repository — the same text armemon writes
 *       into every app, with a note saying where it comes from.
 * WHY:  The in-app copy only exists in apps the CLI made, and the guide's last section
 *       is for people who don't use the CLI at all. They would never see it. So the
 *       repository carries a copy — and generates it from here, because a second
 *       hand-kept copy of a 600-line guide is out of date the first time a command
 *       changes.
 * HOW:  managedReadme for the current layout, plus the command reference built from the
 *       live program. scripts/generate-user-guide.mjs writes it; a test fails when the
 *       file on disk no longer matches.
 * WHEN: `npm run docs:guide`, and the drift test on every run.
 *
 * EXPORTS: buildRepoUserGuide, buildCliReadme
 * DEPENDS ON: commander (types only), @armemon-library/cli-kit, ./commandReference
 * USED BY: scripts/generate-user-guide.mjs, test/userGuideDoc.test.ts
 */

import type { Command } from 'commander';
import { DEFAULT_LAYOUT, managedReadme } from '@armemon-library/cli-kit';
import { buildCommandReference } from './commandReference.js';

export function buildRepoUserGuide(program: Command): string {
  return `<!-- Generated by scripts/generate-user-guide.mjs from the CLI itself. Do not edit by hand: run \`npm run docs:guide\`. -->

> This is the guide armemon writes into every new app as \`armemon/README.md\`.
> It is made from the CLI, so it always matches the current version.

${managedReadme(DEFAULT_LAYOUT)}${buildCommandReference(program)}`;
}

/** The repository, for links that have to work on npm's package page too. */
const REPO_URL = 'https://github.com/armemon-dev/armemon-library';

/**
 * packages/cli-armemon/README.md — the page npm shows for @armemon-library/cli.
 *
 * It was written by hand and fell behind at once: three commands of sixteen,
 * `--verify` described as opt-in after it became the default, and a line saying
 * Windows and macOS were only offered on their own OS when the opposite was true.
 * The command list is now the same generated reference the in-app guide ends with.
 * Links are absolute, because npm's page can't follow a path into the repository.
 */
export function buildCliReadme(program: Command): string {
  return `<!-- Generated by scripts/generate-user-guide.mjs from the CLI itself. Do not edit by hand: run \`npm run docs:guide\`. -->

# @armemon-library/cli

${program.description()}. Pick your plugins, answer a few questions, and get a
fully wired app with nothing left to hand-edit.

## Run it

Without installing anything:

\`\`\`bash
npx @armemon-library/cli init react-native MyApp
\`\`\`

Or install it once. That gives you two commands for the same CLI, \`armemon\` and the
shorter \`memon\`:

\`\`\`bash
npm install -g @armemon-library/cli
\`\`\`

\`\`\`bash
armemon init react-native MyApp
\`\`\`

New to armemon? The [user guide](${REPO_URL}/blob/main/docs/user-guide.md) explains every
command in plain words, what each plugin does, and how to use the plugins without the CLI.
${buildCommandReference(program)}
---

Part of [armemon](${REPO_URL}) — interactive React Native scaffolding.
MIT © Ahmed Raza Memon
`;
}
