/**
 * FILE: babelConfigPatcher.ts
 * PATH: packages/cli-kit/src/fs/babelConfigPatcher.ts
 *
 * WHAT: Writes one babel.config.js composed from every plugin's requested Babel
 *       plugin entries, preserving whatever presets the RN template shipped.
 * WHY:  Babel config was previously patched by whichever step got there first and
 *       described to the user in a postInstallNote by everyone else — the dotenv
 *       step OVERWROTE the file with only its own plugin, while the path-aliases
 *       step asked the user to add module-resolver by hand, and the drawer navigator
 *       asked for reanimated's plugin by hand too. Three features, one file, two of
 *       them manual and one of them clobbering. Since every requested entry is known
 *       at plan time, composing them centrally is both simpler and the only version
 *       that actually delivers "no manual wiring left".
 * HOW:  Parses the presets array out of the existing config with a narrow regex (the
 *       RN template's babel.config.js is a fixed two-line module.exports and has been
 *       for many releases) and falls back to the known default when it doesn't match,
 *       so an unrecognized config never silently loses its presets. Plugin ORDER is
 *       preserved as given: react-native-reanimated/plugin must be last, which the
 *       caller guarantees by sorting `lastPlugins` to the end.
 *
 *       Adding or removing a plugin later is different: by then the file may hold Babel
 *       plugins the person added, and rebuilding it from the plan list would drop them.
 *       addBabelPlugins / removeBabelPlugins edit the `plugins` array in place, through
 *       the parser, and touch nothing else.
 * WHEN: buildBabelConfigSource once at init; the add/remove edits by `armemon plugin`.
 *
 * EXPORTS: buildBabelConfigSource, writeBabelConfig, orderBabelPlugins, addBabelPlugins,
 *          removeBabelPlugins
 * DEPENDS ON: node:path, node:fs/promises, typescript, ./sourceEdit, ./arrayLiteralEdit,
 *             ./patchResult
 * USED BY: packages/cli-armemon/src/flows/initReactNative.ts, flows/plugins/reconcile.ts
 */

import path from 'node:path';
import fs from 'node:fs/promises';
import ts from 'typescript';
import { applyEdits, findProperty, parseSource, propertyInsertion, removalOf, type TextEdit } from './sourceEdit.js';
import { arrayElementInsertion, arrayElementRemoval, sameCode } from './arrayLiteralEdit.js';
import { brokenReason, checked, done, refused, type PatchResult } from './patchResult.js';

const DEFAULT_PRESETS = "['module:@react-native/babel-preset']";

/** react-native-reanimated's plugin is documented as having to be listed last. */
const MUST_BE_LAST = ['react-native-reanimated/plugin'];

function extractPresets(existing: string | null): string {
  if (!existing) return DEFAULT_PRESETS;
  const match = existing.match(/presets:\s*(\[[^\]]*\])/s);
  return match?.[1]?.trim() ?? DEFAULT_PRESETS;
}

export function orderBabelPlugins(plugins: string[]): string[] {
  const unique = [...new Set(plugins)];
  const last = unique.filter((entry) => MUST_BE_LAST.some((tail) => entry.includes(tail)));
  const rest = unique.filter((entry) => !last.includes(entry));
  return [...rest, ...last];
}

export function buildBabelConfigSource(existing: string | null, plugins: string[]): string {
  const presets = extractPresets(existing);
  const ordered = orderBabelPlugins(plugins);

  if (ordered.length === 0) {
    return `module.exports = {\n  presets: ${presets},\n};\n`;
  }

  const body = ordered.map((entry) => `    ${entry},`).join('\n');
  return `// Generated by armemon — every selected plugin's Babel entries, composed
// into one config. react-native-reanimated/plugin is kept last, as its docs require.
module.exports = {
  presets: ${presets},
  plugins: [
${body}
  ],
};
`;
}

export async function writeBabelConfig(appRoot: string, plugins: string[]): Promise<void> {
  const configPath = path.join(appRoot, 'babel.config.js');
  const existing = await fs.readFile(configPath, 'utf8').catch(() => null);
  await fs.writeFile(configPath, buildBabelConfigSource(existing, plugins), 'utf8');
}

/** The object `module.exports` is set to, when the file is that simple shape. */
function exportedConfig(file: ts.SourceFile): ts.ObjectLiteralExpression | null {
  for (const statement of file.statements) {
    if (!ts.isExpressionStatement(statement)) continue;
    const expression = statement.expression;
    if (
      ts.isBinaryExpression(expression) &&
      expression.operatorToken.kind === ts.SyntaxKind.EqualsToken &&
      ts.isPropertyAccessExpression(expression.left) &&
      expression.left.getText(file) === 'module.exports' &&
      ts.isObjectLiteralExpression(expression.right)
    ) {
      return expression.right;
    }
  }
  return null;
}

const manualFor = (entries: string[], verb: 'Add' | 'Remove') =>
  `${verb} ${entries.length === 1 ? 'this entry' : 'these entries'} ${verb === 'Add' ? 'to' : 'from'} the plugins list in babel.config.js: ${entries.join(', ')}`;

/**
 * Adds Babel plugin entries that aren't there yet, before react-native-reanimated's
 * (which has to stay last), leaving every other entry as it is.
 */
export function addBabelPlugins(content: string, entries: string[], fileName = 'babel.config.js'): PatchResult {
  const broken = brokenReason(content, fileName);
  if (broken) return refused(content, broken, manualFor(entries, 'Add'));

  const file = parseSource(content, fileName);
  const config = exportedConfig(file);
  if (!config) {
    return refused(content, "babel.config.js isn't a plain `module.exports = { … }`", manualFor(entries, 'Add'));
  }

  const property = findProperty(config, 'plugins');
  if (property && !ts.isArrayLiteralExpression(property.initializer)) {
    return refused(content, "its `plugins` isn't a plain list", manualFor(entries, 'Add'));
  }
  const array = property?.initializer as ts.ArrayLiteralExpression | undefined;
  const present = array ? array.elements.map((element) => element.getText(file)) : [];
  const missing = orderBabelPlugins(entries).filter((entry) => !present.some((existing) => sameCode(existing, entry)));
  if (missing.length === 0) return done(content, 'babel.config.js already has these entries');

  if (!array) {
    const edits: TextEdit[] = propertyInsertion(content, file, config, 'plugins', `[${orderBabelPlugins(missing).join(', ')}]`);
    return checked(content, applyEdits(content, edits), fileName, manualFor(entries, 'Add'));
  }

  // Before the first entry that must stay last, or at the end.
  const lastIndex = array.elements.findIndex((element) =>
    MUST_BE_LAST.some((tail) => element.getText(file).includes(tail)),
  );
  const isLast = (entry: string) => MUST_BE_LAST.some((tail) => entry.includes(tail));
  const regular = missing.filter((entry) => !isLast(entry));
  const last = missing.filter(isLast);
  const edits: TextEdit[] = [
    ...arrayElementInsertion(content, file, array, regular, lastIndex === -1 ? array.elements.length : lastIndex),
    ...arrayElementInsertion(content, file, array, last, array.elements.length),
  ];
  // Inserted regular entries before an existing last entry AND a new last entry at the
  // end would both be fine; two groups at the same end position are merged instead.
  if (lastIndex === -1 && regular.length > 0 && last.length > 0) {
    return checked(
      content,
      applyEdits(content, arrayElementInsertion(content, file, array, [...regular, ...last], array.elements.length)),
      fileName,
      manualFor(entries, 'Add'),
    );
  }
  return checked(content, applyEdits(content, edits), fileName, manualFor(entries, 'Add'));
}

/** Removes Babel plugin entries, matched as code rather than as text. */
export function removeBabelPlugins(content: string, entries: string[], fileName = 'babel.config.js'): PatchResult {
  const broken = brokenReason(content, fileName);
  if (broken) return refused(content, broken, manualFor(entries, 'Remove'));

  const file = parseSource(content, fileName);
  const config = exportedConfig(file);
  const property = config ? findProperty(config, 'plugins') : undefined;
  if (!config) {
    return refused(content, "babel.config.js isn't a plain `module.exports = { … }`", manualFor(entries, 'Remove'));
  }
  if (!property) return done(content, 'babel.config.js has no plugins to remove');
  if (!ts.isArrayLiteralExpression(property.initializer)) {
    return refused(content, "its `plugins` isn't a plain list", manualFor(entries, 'Remove'));
  }

  const array = property.initializer;
  const matches = array.elements.filter((element) => entries.some((entry) => sameCode(element.getText(file), entry)));
  if (matches.length === 0) return done(content, 'babel.config.js no longer has these entries');

  // Emptied by this removal: the property goes too, back to the shape it had before
  // anything was added. A `plugins: []` someone wrote themselves is never touched.
  const edits =
    matches.length === array.elements.length
      ? [removalOf(content, property.getStart(file), property.getEnd(), { trailingComma: true })]
      : arrayElementRemoval(content, file, array, matches);
  return checked(content, applyEdits(content, edits), fileName, manualFor(entries, 'Remove'));
}
