/**
 * FILE: removeScreen.test.ts
 * PATH: packages/cli-armemon/test/removeScreen.test.ts
 *
 * WHAT: `armemon remove-screen` on apps generated by init.
 * WHY:  Removing is the destructive direction. What matters is that it undoes
 *       create-screen exactly — no stray import, no leftover param entry, no orphaned
 *       link — and that it refuses while other code would break, saying where.
 */
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { runCreateScreenFlow, runRemoveScreenFlow } from '../dist/index.js';
import { NAV, captureStdout, makeApp, resetCliState, scaffoldNavigation, writeConfig, type TestApp } from './support/screenApps';

let app: TestApp;

beforeEach(async () => {
  app = await makeApp();
});
afterEach(async () => {
  resetCliState();
  await app.remove();
});

const create = (name: string, over: Record<string, unknown> = {}) =>
  runCreateScreenFlow({ name, cwd: app.root, allAccept: true, full: true, verify: false, ...over } as never);
const remove = (name: string, over: Record<string, unknown> = {}) =>
  runRemoveScreenFlow({ name, cwd: app.root, allAccept: true, verify: false, ...over } as never);

const FILES = [`${NAV}/RootNavigator.tsx`, `${NAV}/types.ts`, `${NAV}/navigation.config.ts`];
const snapshot = () => Promise.all(FILES.map((file) => app.read(file)));

describe('remove-screen', () => {
  it('undoes create-screen exactly, in every file', async () => {
    await scaffoldNavigation(app);
    const before = await snapshot();

    await create('Order');
    await remove('Order');

    expect(await snapshot()).toEqual(before);
    expect(await app.exists('src/screens/OrderScreen')).toBe(false);
  });

  it('undoes a tab screen with params and a nested link just as exactly', async () => {
    await scaffoldNavigation(app, { navigatorType: 'stack-with-tabs' });
    const before = await snapshot();

    await create('Order', { navigator: 'tabs', link: 'order/:id', params: 'id:number' });
    await remove('Order');

    expect(await snapshot()).toEqual(before);
  });

  it('refuses while another screen still navigates to it, and says where', async () => {
    await scaffoldNavigation(app);
    await create('Order');
    await app.write(
      'src/screens/HomeScreen/index.tsx',
      "import { useNavigation } from '@react-navigation/native';\n\nexport default function HomeScreen() {\n  const navigation = useNavigation();\n  navigation.navigate('Order');\n  return null;\n}\n",
    );

    await expect(remove('Order')).rejects.toThrow("One place still uses Order:\n  src/screens/HomeScreen/index.tsx:5  navigation.navigate('Order');");
    expect(await app.read(`${NAV}/RootNavigator.tsx`)).toContain('name="Order"');
    expect(await app.exists('src/screens/OrderScreen')).toBe(true);

    const summary = JSON.parse(await captureStdout(() => remove('Order', { force: true, json: true })));
    expect(summary).toMatchObject({ ok: true, deletedFolder: true });
    expect(summary.references).toEqual([
      { file: 'src/screens/HomeScreen/index.tsx', line: 5, kind: 'navigate', text: "navigation.navigate('Order');" },
    ]);
    expect(await app.read(`${NAV}/RootNavigator.tsx`)).not.toContain('name="Order"');
  });

  it('refuses the initial route unless forced, then lets the next screen open first', async () => {
    await scaffoldNavigation(app);
    await expect(remove('Home')).rejects.toThrow(/"Home" is the initial route of <Stack.Navigator>/);

    await remove('Home', { force: true });
    const navigator = await app.read(`${NAV}/RootNavigator.tsx`);
    expect(navigator).toContain('<Stack.Navigator>');
    expect(navigator).not.toContain('HomeScreen');
    expect(await app.read(`${NAV}/types.ts`)).not.toContain('Home: undefined');
  });

  it('refuses to leave a navigator with no screens', async () => {
    await writeConfig(app);
    await app.write(
      `${NAV}/RootNavigator.tsx`,
      "import React from 'react';\nimport { createNativeStackNavigator } from '@react-navigation/native-stack';\nimport HomeScreen from '../../src/screens/HomeScreen';\n\nconst Stack = createNativeStackNavigator();\n\nexport default function RootNavigator() {\n  return (\n    <Stack.Navigator>\n      <Stack.Screen name=\"Home\" component={HomeScreen} />\n    </Stack.Navigator>\n  );\n}\n",
    );
    await expect(remove('Home')).rejects.toThrow(/"Home" is the only screen in <Stack.Navigator>/);
  });

  it('refuses to remove a route that renders a whole navigator, even with --force', async () => {
    await scaffoldNavigation(app, { navigatorType: 'stack-with-tabs' });
    await create('Details', { navigator: 'stack' });
    const before = await snapshot();

    for (const force of [false, true]) {
      await expect(remove('Tabs', { force })).rejects.toThrow(
        '"Tabs" renders <Tab.Navigator> (armemon/navigation/RootNavigator.tsx), with Home, Screen2.',
      );
    }
    expect(await snapshot()).toEqual(before);
  });

  it('stops before writing when the registration itself cannot be removed safely, even with --force', async () => {
    await scaffoldNavigation(app);
    const navigator = await app.read(`${NAV}/RootNavigator.tsx`);
    await app.write(
      `${NAV}/RootNavigator.tsx`,
      navigator.replace('      <Stack.Screen name="Screen2" component={Screen2Screen} />', '      {true && <Stack.Screen name="Screen2" component={Screen2Screen} />}'),
    );
    const before = await snapshot();

    await expect(remove('Screen2', { force: true })).rejects.toThrow(
      /Can't remove Screen2 from armemon\/navigation\/RootNavigator\.tsx: the "Screen2" screen sits inside an expression/,
    );
    expect(await snapshot()).toEqual(before);
    expect(await app.exists('src/screens/Screen2Screen')).toBe(true);
  });

  it('with --force, keeps a folder other files still import from', async () => {
    await scaffoldNavigation(app);
    await create('Order');
    await app.write('src/screens/OrderScreen/components/OrderRow.tsx', 'export default function OrderRow() {\n  return null;\n}\n');
    await app.write('src/screens/HomeScreen/index.tsx', "import OrderRow from '../OrderScreen/components/OrderRow';\n\nexport default function HomeScreen() {\n  return OrderRow;\n}\n");

    const summary = JSON.parse(await captureStdout(() => remove('Order', { force: true, json: true })));
    expect(summary).toMatchObject({ ok: false, deletedFolder: false });
    expect(summary.edits).toContainEqual(expect.objectContaining({
      file: 'src/screens/OrderScreen',
      status: 'skipped',
      reason: expect.stringMatching(/a file still imports from it/),
    }));
    expect(await app.exists('src/screens/OrderScreen/components/OrderRow.tsx')).toBe(true);
    expect(await app.read(`${NAV}/RootNavigator.tsx`)).not.toContain('name="Order"');
  });

  it('lists URLs that still open the removed deep link', async () => {
    await scaffoldNavigation(app);
    await create('Order', { link: 'order' });
    await app.write('src/screens/HomeScreen/index.tsx', "import { useLinkTo } from '@react-navigation/native';\n\nexport default function HomeScreen() {\n  const linkTo = useLinkTo();\n  linkTo('/order');\n  return null;\n}\n");

    const summary = JSON.parse(await captureStdout(() => remove('Order', { json: true })));
    expect(summary.ok).toBe(true);
    expect(summary.staleLinks).toEqual([{ file: 'src/screens/HomeScreen/index.tsx', line: 5, text: "linkTo('/order');" }]);
  });

  it('takes a removed screen out of an import it shares with others', async () => {
    await writeConfig(app);
    await app.write(
      `${NAV}/RootNavigator.tsx`,
      "import React from 'react';\nimport { createNativeStackNavigator } from '@react-navigation/native-stack';\nimport { HomeScreen, OrderScreen } from '../../screens';\n\nconst Stack = createNativeStackNavigator();\n\nexport default function RootNavigator() {\n  return (\n    <Stack.Navigator>\n      <Stack.Screen name=\"Home\" component={HomeScreen} />\n      <Stack.Screen name=\"Order\" component={OrderScreen} />\n    </Stack.Navigator>\n  );\n}\n",
    );
    await app.write('src/screens/index.ts', "export { default as HomeScreen } from './HomeScreen';\nexport { default as OrderScreen } from './OrderScreen';\n");
    await app.write('src/screens/HomeScreen/index.tsx', 'export default function HomeScreen() {\n  return null;\n}\n');
    await app.write('src/screens/OrderScreen/index.tsx', 'export default function OrderScreen() {\n  return null;\n}\n');

    await remove('Order', { force: true });
    expect(await app.read(`${NAV}/RootNavigator.tsx`)).toContain("import { HomeScreen } from '../../screens';");
  });

  it('takes the screen out of a barrel that re-exports it, and deletes the folder', async () => {
    await writeConfig(app);
    await app.write(
      `${NAV}/RootNavigator.tsx`,
      "import React from 'react';\nimport { createNativeStackNavigator } from '@react-navigation/native-stack';\nimport { HomeScreen, OrderScreen } from '../../screens';\n\nconst Stack = createNativeStackNavigator();\n\nexport default function RootNavigator() {\n  return (\n    <Stack.Navigator>\n      <Stack.Screen name=\"Home\" component={HomeScreen} />\n      <Stack.Screen name=\"Order\" component={OrderScreen} />\n    </Stack.Navigator>\n  );\n}\n",
    );
    await app.write('src/screens/index.ts', "export { default as HomeScreen } from './HomeScreen';\nexport { default as OrderScreen } from './OrderScreen';\n");
    await app.write('src/screens/HomeScreen/index.tsx', 'export default function HomeScreen() {\n  return null;\n}\n');
    await app.write('src/screens/OrderScreen/index.tsx', 'export default function OrderScreen() {\n  return null;\n}\n');

    await remove('Order');
    expect(await app.read('src/screens/index.ts')).toBe("export { default as HomeScreen } from './HomeScreen';\n");
    expect(await app.read(`${NAV}/RootNavigator.tsx`)).toContain("import { HomeScreen } from '../../screens';");
    expect(await app.exists('src/screens/OrderScreen')).toBe(false);
  });

  it('keeps a barrel line something still imports through the barrel', async () => {
    await scaffoldNavigation(app);
    await create('Order');
    await app.write('src/screens/index.ts', "export { default as OrderScreen } from './OrderScreen';\n");
    await app.write('src/screens/HomeScreen/index.tsx', "import { OrderScreen } from '..';\n\nexport default function HomeScreen() {\n  return OrderScreen;\n}\n");

    await expect(remove('Order')).rejects.toThrow(/src\/screens\/index\.ts:1/);
  });

  it('is not blocked by strings that only look like the route', async () => {
    await scaffoldNavigation(app);
    await create('Order');
    await app.write('src/utils/misc.ts', "export function f(tags: string[], text: string) {\n  tags.push('Order');\n  return text.replace('Order', 'x');\n}\n");

    await remove('Order');
    expect(await app.exists('src/screens/OrderScreen')).toBe(false);
  });

  it('removes a tab screen from its navigator, its param list and its nested link', async () => {
    await scaffoldNavigation(app, { navigatorType: 'stack-with-tabs' });
    await remove('Screen2');

    expect(await app.read(`${NAV}/RootNavigator.tsx`)).not.toMatch(/name="Screen2"|import Screen2Screen/);
    expect(await app.read(`${NAV}/types.ts`)).toContain('export type TabParamList = {\n  Home: undefined;\n};');
    expect(await app.read(`${NAV}/navigation.config.ts`)).not.toContain("Screen2: 'Screen2'");
    expect(await app.exists('src/screens/Screen2Screen')).toBe(false);
  });

  it('--keep-files unregisters but leaves the folder', async () => {
    await scaffoldNavigation(app);
    await create('Order');
    await remove('Order', { keepFiles: true });

    expect(await app.read(`${NAV}/RootNavigator.tsx`)).not.toContain('Order');
    expect(await app.exists('src/screens/OrderScreen/index.tsx')).toBe(true);
  });

  it('--dry-run changes nothing', async () => {
    await scaffoldNavigation(app);
    await create('Order');
    const before = await snapshot();

    const summary = JSON.parse(await captureStdout(() => remove('Order', { dryRun: true, json: true })));
    expect(summary).toMatchObject({ ok: true, dryRun: true, deletedFolder: true });
    expect(await snapshot()).toEqual(before);
    expect(await app.exists('src/screens/OrderScreen')).toBe(true);
  });

  it('says so when there is no such screen', async () => {
    await scaffoldNavigation(app);
    await expect(remove('Nope')).rejects.toThrow(/There's no Nope screen/);
  });
});
