/**
 * FILE: renameScreen.test.ts
 * PATH: packages/cli-armemon/test/renameScreen.test.ts
 *
 * WHAT: `armemon rename-screen` on apps generated by init.
 * WHY:  A rename touches more places than any other screen change, and in a
 *       JavaScript app a missed one still runs — until someone taps it. So this checks
 *       every place a name lives, that a title which merely says "Order" is reported
 *       and left alone, and that a deep-link path follows the name only when it came
 *       from the name.
 */
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { normalizeScreenName } from '@armemon-library/cli-kit';
import { renamedLinkPath, runCreateScreenFlow, runRenameScreenFlow } from '../dist/index.js';
import { NAV, captureStdout, makeApp, resetCliState, scaffoldNavigation, type TestApp } from './support/screenApps';

let app: TestApp;

beforeEach(async () => {
  app = await makeApp();
});
afterEach(async () => {
  resetCliState();
  await app.remove();
});

const create = (name: string, over: Record<string, unknown> = {}) =>
  runCreateScreenFlow({ name, cwd: app.root, allAccept: true, full: true, verify: false, ...over } as never);
const rename = (from: string, to: string, over: Record<string, unknown> = {}) =>
  runRenameScreenFlow({ from, to, cwd: app.root, allAccept: true, verify: false, ...over } as never);

describe('rename-screen', () => {
  it('renames the folder, component, route, types, link and every navigate() call', async () => {
    await scaffoldNavigation(app);
    await create('Order');
    await app.write('src/screens/OrderScreen/components/OrderRow.tsx', 'export default function OrderRow() {\n  return null;\n}\n');
    await app.write(
      'src/screens/HomeScreen/index.tsx',
      "import { useNavigation } from '@react-navigation/native';\nimport OrderRow from '../OrderScreen/components/OrderRow';\n\nexport default function HomeScreen() {\n  const navigation = useNavigation();\n  const title = 'Order';\n  navigation.navigate('Order');\n  return OrderRow && title;\n}\n",
    );

    const summary = JSON.parse(await captureStdout(() => rename('Order', 'Invoice', { json: true })));
    expect(summary).toMatchObject({ ok: true, movedFolder: true, linkingPath: { from: 'Order', to: 'Invoice' } });
    expect(summary.unhandled).toEqual([{ file: 'src/screens/HomeScreen/index.tsx', line: 6, text: "const title = 'Order';" }]);

    expect(await app.exists('src/screens/OrderScreen')).toBe(false);
    const screen = await app.read('src/screens/InvoiceScreen/index.tsx');
    expect(screen).toContain('export default function InvoiceScreen()');
    expect(screen).toContain("navigation.navigate('Invoice');");
    expect(screen).toContain('<Text>Invoice</Text>');
    expect(await app.read('src/screens/InvoiceScreen/components/README.md')).toContain('# InvoiceScreen / components');
    expect(await app.exists('src/screens/InvoiceScreen/components/OrderRow.tsx')).toBe(true);

    const navigator = await app.read(`${NAV}/RootNavigator.tsx`);
    expect(navigator).toContain("import InvoiceScreen from '../../src/screens/InvoiceScreen';");
    expect(navigator).toContain('<Stack.Screen name="Invoice" component={InvoiceScreen} />');
    expect(navigator).not.toContain('Order');

    const types = await app.read(`${NAV}/types.ts`);
    expect(types).toContain('  Invoice: undefined;');
    expect(types).not.toContain('Order');
    expect(await app.read(`${NAV}/navigation.config.ts`)).toContain("      Invoice: 'Invoice',");

    const home = await app.read('src/screens/HomeScreen/index.tsx');
    expect(home).toContain("navigation.navigate('Invoice');");
    expect(home).toContain("import OrderRow from '../InvoiceScreen/components/OrderRow';");
    expect(home).toContain("const title = 'Order';");
  });

  it('moves a path derived from the old name, and keeps one chosen by hand', async () => {
    await scaffoldNavigation(app);
    await create('Order', { link: 'order/:id' });
    await create('Cart', { link: 'checkout' });

    await rename('Order', 'Invoice');
    await rename('Cart', 'Basket');

    const linking = await app.read(`${NAV}/navigation.config.ts`);
    expect(linking).toContain("Invoice: 'invoice/:id',");
    expect(linking).toContain("Basket: 'checkout',");
    expect(await app.read(`${NAV}/types.ts`)).toContain('  Invoice: { id: string };');
    expect(await app.read('src/screens/InvoiceScreen/index.tsx')).toContain("type Props = NativeStackScreenProps<RootStackParamList, 'Invoice'>;");
  });

  it('renames a tab screen inside its tab list and nested link', async () => {
    await scaffoldNavigation(app, { navigatorType: 'stack-with-tabs' });
    await rename('Screen2', 'Feed');

    const navigator = await app.read(`${NAV}/RootNavigator.tsx`);
    expect(navigator).toContain('<Tab.Screen name="Feed" component={FeedScreen} />');
    expect(navigator).toContain("import FeedScreen from '../../src/screens/FeedScreen';");
    expect(await app.read(`${NAV}/types.ts`)).toContain('export type TabParamList = {\n  Home: undefined;\n  Feed: undefined;\n};');
    expect(await app.read(`${NAV}/navigation.config.ts`)).toContain("          Feed: 'Feed',");
    expect(await app.read('src/screens/FeedScreen/index.tsx')).toContain('export default function FeedScreen()');
  });

  it('renames a route that renders a navigator, including the linking key its links hang off', async () => {
    await scaffoldNavigation(app, { navigatorType: 'stack-with-tabs' });
    await rename('Tabs', 'Main');

    expect(await app.read(`${NAV}/navigation.config.ts`)).toContain("      Main: {\n        screens: {\n          Home: 'Home',");
    expect(await app.read(`${NAV}/RootNavigator.tsx`)).toContain('<Stack.Screen name="Main" component={Tabs} />');
    expect(await app.read(`${NAV}/types.ts`)).toContain('  Main: NavigatorScreenParams<TabParamList>;');
  });

  it('updates the old name in the doc comments of the files it touches', async () => {
    await scaffoldNavigation(app);
    await rename('Screen2', 'Feed');
    expect(await app.read(`${NAV}/RootNavigator.tsx`)).not.toContain('Screen2');
  });

  it('updates a route passed through a conditional', async () => {
    await scaffoldNavigation(app);
    await app.write('src/screens/HomeScreen/index.tsx', "import { useNavigation } from '@react-navigation/native';\n\nexport default function HomeScreen({ ready }: { ready: boolean }) {\n  const navigation = useNavigation();\n  navigation.navigate(ready ? 'Screen2' : 'Home');\n  return null;\n}\n");
    await rename('Screen2', 'Feed');
    expect(await app.read('src/screens/HomeScreen/index.tsx')).toContain("navigation.navigate(ready ? 'Feed' : 'Home');");
  });

  it('refuses a name that is already taken', async () => {
    await scaffoldNavigation(app);
    await expect(rename('Screen2', 'Home')).rejects.toThrow(/src\/screens\/HomeScreen already exists/);
  });

  it('--dry-run writes nothing', async () => {
    await scaffoldNavigation(app);
    await create('Order');
    const before = await app.read(`${NAV}/RootNavigator.tsx`);

    const summary = JSON.parse(await captureStdout(() => rename('Order', 'Invoice', { dryRun: true, json: true })));
    expect(summary).toMatchObject({ ok: true, dryRun: true });
    expect(await app.read(`${NAV}/RootNavigator.tsx`)).toBe(before);
    expect(await app.exists('src/screens/OrderScreen/index.tsx')).toBe(true);
    expect(await app.exists('src/screens/InvoiceScreen')).toBe(false);
  });

  it('refuses --link with --keep-link', async () => {
    await scaffoldNavigation(app);
    await expect(rename('Screen2', 'Feed', { link: 'feed', keepLink: true })).rejects.toThrow(/--link and --keep-link contradict/);
  });
});

describe('rename-screen and code that only looks like the route', () => {
  it('leaves strings and types that are not navigation alone', async () => {
    await scaffoldNavigation(app);
    await create('Order');
    const misc = "export type Status = 'Order' | 'Cart';\nexport type NotOrder = Exclude<Status, 'Order'>;\nexport function f(text: string, tags: string[], form: { reset(v: object): void }) {\n  tags.push('Order');\n  form.reset({ name: 'Order' });\n  return text.replace('Order', 'x');\n}\n";
    await app.write('src/utils/misc.ts', misc);

    await rename('Order', 'Invoice');
    expect(await app.read('src/utils/misc.ts')).toBe(misc);
  });

  it('lists URLs that still open the old deep link', async () => {
    await scaffoldNavigation(app);
    await create('Order', { link: 'order' });
    await app.write('src/screens/HomeScreen/index.tsx', "import { useLinkTo } from '@react-navigation/native';\n\nexport default function HomeScreen() {\n  const linkTo = useLinkTo();\n  linkTo('/order');\n  return null;\n}\n");

    const summary = JSON.parse(await captureStdout(() => rename('Order', 'Invoice', { json: true })));
    expect(summary.linkingPath).toEqual({ from: 'order', to: 'invoice' });
    expect(summary.staleLinks).toEqual([{ file: 'src/screens/HomeScreen/index.tsx', line: 5, text: "linkTo('/order');" }]);
  });

  it('renames named imports and exports of the component', async () => {
    await scaffoldNavigation(app);
    await create('Order');
    const index = await app.read('src/screens/OrderScreen/index.tsx');
    await app.write('src/screens/OrderScreen/index.tsx', `${index}\nexport { OrderScreen };\n`);
    await app.write('src/screens/HomeScreen/index.tsx', "import { OrderScreen } from '../OrderScreen';\n\nexport default function HomeScreen() {\n  return OrderScreen;\n}\n");

    await rename('Order', 'Invoice');
    expect(await app.read('src/screens/InvoiceScreen/index.tsx')).toContain('export { InvoiceScreen };');
    expect(await app.read('src/screens/HomeScreen/index.tsx')).toBe(
      "import { InvoiceScreen } from '../InvoiceScreen';\n\nexport default function HomeScreen() {\n  return InvoiceScreen;\n}\n",
    );
  });
});

describe('renamedLinkPath', () => {
  const name = (value: string) => normalizeScreenName(value);

  it.each([
    ['Order', 'Order', 'Invoice', 'Invoice'],
    ['order', 'Order', 'Invoice', 'invoice'],
    ['order/:id', 'Order', 'Invoice', 'invoice/:id'],
    ['order-history/:id', 'OrderHistory', 'PastOrders', 'past-orders/:id'],
    ['tyt', 'tytScreen', 'fooScreen', 'foo'],
    ['checkout', 'Cart', 'Basket', 'checkout'],
  ])('%j, renaming %s to %s, becomes %j', (current, from, to, expected) => {
    expect(renamedLinkPath(current, name(from), name(to))).toBe(expected);
  });
});
