/**
 * FILE: userGuideDoc.test.ts
 * PATH: packages/cli-armemon/test/userGuideDoc.test.ts
 *
 * WHAT: docs/user-guide.md matches what the CLI would generate right now.
 * WHY:  That file is the only place someone using the plugins without the CLI will
 *       find the guide. It is generated, so the only way it goes stale is somebody
 *       changing a command or the guide text and not regenerating — which is exactly
 *       what this catches, with the command that fixes it in the failure message.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { buildCliReadme, buildRepoUserGuide, createProgram } from '../dist/index.js';

const ROOT = fileURLToPath(new URL('../../..', import.meta.url));

describe('docs/user-guide.md', () => {
  it('is up to date with the CLI', async () => {
    const onDisk = await fs.readFile(path.join(ROOT, 'docs/user-guide.md'), 'utf8').catch(() => null);

    expect(onDisk, 'docs/user-guide.md is missing — run: npm run docs:guide').not.toBeNull();
    expect(onDisk === buildRepoUserGuide(createProgram([])), 'docs/user-guide.md is out of date — run: npm run docs:guide').toBe(true);
  });

  it('says where it comes from, so nobody edits it by hand', async () => {
    const onDisk = await fs.readFile(path.join(ROOT, 'docs/user-guide.md'), 'utf8');
    expect(onDisk).toMatch(/^<!-- Generated by scripts\/generate-user-guide\.mjs/);
  });
});

describe('packages/cli-armemon/README.md', () => {
  // The page npm shows. Hand-kept, it listed three commands of sixteen.
  it('is up to date with the CLI', async () => {
    const onDisk = await fs.readFile(path.join(ROOT, 'packages/cli-armemon/README.md'), 'utf8').catch(() => null);
    expect(
      onDisk === buildCliReadme(createProgram([])),
      'packages/cli-armemon/README.md is out of date — run: npm run docs:guide',
    ).toBe(true);
  });

  it('lists every command, and links only to absolute URLs npm can follow', () => {
    const readme = buildCliReadme(createProgram([]));
    for (const command of createProgram([]).commands) {
      expect(readme, command.name()).toContain(`armemon ${command.name()}`);
    }
    const relativeLinks = [...readme.matchAll(/\]\((?!https?:|#)([^)]+)\)/g)].map((match) => match[1]);
    expect(relativeLinks).toEqual([]);
  });
});
